### ISSUE TITLE
Modifications to classpath by middleware are not visible to user nREPL session

### ISSUE THREAD

**Issue by jeffvalk** [clojure-emacs/orchard#103]
### Summary

Middleware is loaded in a different classloader context than user interactions with that middleware. The latter shares no modifiable classloader parent with the former, so changes made to the classpath when middleware is loaded are not seen by user interactions.

### Impact
The primary example of this is in `java.clj`, which adds the JDK `src.zip` to the classpath and sets the `jdk-sources` variable to the zip file's path if found. In-editor JDK class/method docstrings (and argument names, etc) depends on this feature, as does source navigation (jumping) for JDK classes.

The following issues appear to describe this bug:

- https://github.com/clojure-emacs/cider/issues/2732
- https://github.com/clojure-emacs/cider/issues/2687
- https://github.com/clojure-emacs/cider-nrepl/issues/687

### Scope

This behavior happens on both JDK8 and 9+. `dynapath` formerly hacked `java.net.URLClassLoader` to allow it to be modifiable on JDK8 and below, which would have prevented this issue on JDK8 (albeit in an unsupported way), but recent versions of `dynapath` removed this hack, so all JDK versions behave the same wrt this issue.

### Investigation

Below are the values of `jdk-sources`, the classpath, and the classloader hierarchy at middleware load time (via print statements in the `java` middleware), and at runtime in a user REPL session. Note that:

1. Both contexts reflect that `src.zip` has been found (`jdk-sources` is set); however
2. `src.zip` is visible on the classpath at load time, but not at runtime in the REPL session, because 
3. there is no shared `DynamicClassLoader` in their respective classloader hierarchies. The lowest common ancestor of the context classloader for these contexts is an `AppClassLoader`, which is not modifiable. Hence, any modification to the highest modifiable classloader in the first context is not visible in the second.

At load time:

```
;; jdk-sources
#object[java.net.URL 0x2199cb1b file:/usr/lib/jvm/java-11-openjdk/lib/src.zip]

;; classpath
(;; ...all identical to below, except this entry is present:
 #object[java.net.URL 0x2199cb1b "file:/usr/lib/jvm/java-11-openjdk/lib/src.zip"])

;; classloaders
(#object[clojure.lang.DynamicClassLoader 0x6d6bc158 "clojure.lang.DynamicClassLoader@6d6bc158"]
 #object[jdk.internal.loader.ClassLoaders$AppClassLoader 0x277050dc "jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc"]
 #object[jdk.internal.loader.ClassLoaders$PlatformClassLoader 0x5825f15a "jdk.internal.loader.ClassLoaders$PlatformClassLoader@5825f15a"])
```

And at runtime, via the REPL:

```
;; jdk-sources
#object[java.net.URL 0x2199cb1b file:/usr/lib/jvm/java-11-openjdk/lib/src.zip]

;; classpath
(;; ...all identical to above, but missing the added src.zip classpath entry
)

;; classloaders
(#object[clojure.lang.DynamicClassLoader 0x8424570 "clojure.lang.DynamicClassLoader@8424570"]
 #object[clojure.lang.DynamicClassLoader 0x69433f24 "clojure.lang.DynamicClassLoader@69433f24"]
 #object[clojure.lang.DynamicClassLoader 0x48d3a104 "clojure.lang.DynamicClassLoader@48d3a104"]
 #object[clojure.lang.DynamicClassLoader 0x5367dcfe "clojure.lang.DynamicClassLoader@5367dcfe"]
 #object[jdk.internal.loader.ClassLoaders$AppClassLoader 0x277050dc "jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc"]
 #object[jdk.internal.loader.ClassLoaders$PlatformClassLoader 0x5825f15a "jdk.internal.loader.ClassLoaders$PlatformClassLoader@5825f15a"])
```
### Analysis

This may be as much an nREPL discussion as an orchard one. I suspect it may have to do with `*bindings*` (including the `clojure.lang.Compiler/LOADER`) being stored and passed as the `:session` for nREPL messages -- essentially that these contexts are intentionally separated.

If so, testing for correct behavior requires *both* contexts. It can't be tested purely within a CIDER/nREPL session (as one would do in development), nor would our current approach to unit tests catch any breakage.

At a high level, there seem to be two ways to make this behave as intended:
1. Propagate changes to the classpath made at load time into each new nREPL session (likely by pushing the classloader or a descendant classloader into the session); or
2. Change the logic in orchard such that each nREPL session makes its own changes to the classpath.

@bbatsov What do you think of this?

**Comment by jeffvalk** [comment]
Having thought about it for a short bit, I think option 1 above better achieves the principle of least astonishment. I think any middleware author would expect the user's session to reflect any explicit classpath changes made by the middleware. I know I did. Understanding the current behavior was a brain teaser.

**Comment by bbatsov** [comment]
Great investigation, @jeffvalk! Thanks for tracking down the root cause of this. I guess this has been broken ever since the update to dynapath 1.0. 

I also prefer option 1).

**Comment by vemv** [comment]
Hi, I'd like to contribute a question/observation: to what extent is runtime classpath modification a core need of Orchard?

I say this because, like other Clojure developers, I feel a bit wary of fiddling much with classloaders. For example I contributed https://github.com/clojure-emacs/cider-nrepl/pull/668 - a POC showing that the mere presence of CIDER can affect _other_ code.

One can also make the observation that neither Lein or deps.edn officially provide runtime classpath modification. clj-refactor also [disabled it](https://github.com/clojure-emacs/clj-refactor.el/blob/9dcc50da7ce6f3c10276c87f09022e80c03e8bef/clj-refactor.el#L2964-L2971) at some point.

If the extent of this runtime classpath modification is "provide sources and javadocs", one can consider alternatives. I have completed this Lein plugin which accomplishes so https://github.com/clojure-emacs/cider-nrepl/issues/64#issuecomment-752921557 using traditional means - the classpath is _calculated beforehand_ instead of mutated.

If there are no other use cases, it might be worth considering if Orchard's internals can be simplified. This can have other desirable effects, e.g. newcomers can understand better its execution model (since not everyone has expertise in JDK or classloader intricacies).

**Comment by jeffvalk** [comment]
Personally, I'd say the current use case is something any development environment would want. In-editor documentation and source navigation for JDK classes seem like core requirements to me.

As best I can tell, the alternative to the current approach would be adding the `src.zip` path manually to your `project.clj` or `deps.edn` for every project. If you develop/test against multiple Java versions, you'd have to manage that by hand for each project too.

Regarding using a lein plugin to replace this specific use case:

- The JDK and its sources are not ordinary project dependencies. Unlike artifacts installed from a maven (or similar) repository, these are effectively user-provided (installed either manually or using an OS package manager). The possible variations in JDK vendor and release is very large. There is no standard way to find and download JDK sources given a java version string, so a plugin would have a difficult time accomplishing this.
- Leiningen is one of several ways to launch a clojure project. The others would need a solution too.

Regarding avoiding classpath dynamism:

- Clojure itself depends on dynamic classloading, so regardless, we can't reasonably say we stay away from this. We should definitely not use sneaky hacks, but there's no reason to shy away from using (correctly implemented) dynamism in a dynamic language.
- The part about sneaky hacks is important here, because it's the root of this issue. Prior to Java 9, sneakily hacking the application classloader was pervasive in Java tooling. Java 9 put an abrupt stop to this: it broke stuff left and right. :laughing: People turned broken things off. And here we are cleaning up.

**Comment by vemv** [comment]
Thanks for the reply!

> There is no standard way to find and download JDK sources given a java version string, so a plugin would have a difficult time accomplishing this.

A Lein plugin can do arbitrary computation, so the existing logic for finding `src.zip` could be replicated.

There's the precedent of https://github.com/pallet/lein-jdk-tools which does a similar job (although more basic: it doesn't download any files since often they are already included when installing the JDK).

> Leiningen is one of several ways to launch a clojure project. The others would need a solution too.

Yes. The plugin I linked to was written just a couple weeks ago. It's a vanilla Clojure program (it doesn't _need_ `:eval-in-leiningen`) so it could be trivially ported to deps.edn. I think the 'deps.edn way' is simply feeding the output of a program to https://clojure.org/reference/deps_and_cli#_make_classpath_modifiers .

> but there's no reason to shy away from using (correctly implemented) dynamism in a dynamic language.

The language may be dynamic, but the platform can have some constraints...

> The part about sneaky hacks is important here, because it's the root of this issue.

Agreed. I'd humbly suggest to make sure we're not repeating errors:

* is the classpath supposed to be mutable?
* are runtime-extensible classloaders a clean, working reality in JDK9+?
  * e.g. [add-lib](https://github.com/clojure/tools.deps.alpha/commit/40e32378c8ae829b0d07168d365a53bac35ee1f1) work started almost 3 years ago - maybe it's not that feasible?
 
In constrast, Lein's approach of doing classpath calculations "ahead-of-time" seems very much time-proven, well-aligned with JVM's assumptions and compatible with other plugins like deps.edn.

**Comment by bbatsov** [comment]
> One can also make the observation that neither Lein or deps.edn officially provide runtime classpath modification. clj-refactor also disabled it at some point.

I'll just add here that the only reason why this got disabled is that Java 9 broke it. The users loved this functionality and I think it was quite useful. 

> In constrast, Lein's approach of doing classpath calculations "ahead-of-time" seems very much time-proven, well-aligned with JVM's assumptions and compatible with other plugins like deps.edn.

I agree this approach works fine the use case with sources, although knowing how often users are asking for such functionality, not to mention this is at the heart of nREPL's sideloading, which obviously can't be achieved otherwise.

**Comment by bbatsov** [comment]
I'll also add that it seems to me our real issue is that lack of time - we're not really facing any insurmountable issues, but there's a lot of work to go around and no one has much time to dedicate to it. That's why breaking changes often go unaddressed for years (e.g. the ClojureScript completion has also been broken for a while, after some changes were done to shadow-cljs and the maintainer of compliment didn't have time to address those). I myself, try to focus more on the Elisp code, as there are fewer people willing to touch it, compared to those that might fix something occassionallly in `cider-nrepl` and `orchard`.

**Comment by jeffvalk** [comment]
> - is the classpath supposed to be mutable?
> - are runtime-extensible classloaders a clean, working reality in JDK9+?

Yes and yes. This is core Java platform functionality. Application servers and all manner of "enterprise" Java depend on this design. And every time we load a clojure file or evaluate a statement at the REPL, we use it.

**Comment by jeffvalk** [comment]
Finally tracked this one down.

When the nREPL session middleware creates the session classloader, it passes the context classloader as the parent [here][1] and [here][2]. At the time middleware is loaded, the context classloader is the application classloader, which is not modifiable.

For the session to see classpath modifications made when middleware is loaded, two things must be true:

1. The middleware that modifies the classpath must obtain a reference to a dynamic classloader whenever the context classloader is not modifiable. Orchard already does this (see [here][3]), though some improvement may be useful.
2. The session must have this dynamic classloader in its classloader hierarchy. This can be enabled by changing this:

```clj
(clojure.lang.DynamicClassLoader.
  (.getContextClassLoader (Thread/currentThread))) ; <- jdk.internal.loader.ClassLoaders$AppClassLoader
```

to something like this:

```clj
(clojure.lang.DynamicClassLoader.
  @clojure.lang.Compiler/LOADER) ; <- clojure.lang.DynamicClassLoader
```

when creating the nREPL session. I say "something like" because in practice, I'd suggest we use the highest modifiable parent in the compiler's hierarchy, not the lowest.


[1]: https://github.com/nrepl/nrepl/blob/d011098bd8c1a762f19b15b9c0ca10412167ad1b/src/clojure/nrepl/middleware/session.clj#L49

[2]: https://github.com/nrepl/nrepl/blob/d011098bd8c1a762f19b15b9c0ca10412167ad1b/src/clojure/nrepl/middleware/session.clj#L193

[3]: https://github.com/clojure-emacs/orchard/blob/80cd021b05816ecd6b5d1ac6ba66575b695a8a17/src/orchard/java/classpath.clj#L73-L75

**Comment by jeffvalk** [comment]
Before making any changes, it probably makes sense to ask again whether this is the best way to address this.

An alternative would be to make modifications to the classpath within the session. Would this better reflect what a session is designed to do? The tradeoff is that this would create a specific dependency on the session middleware, and the session object would have to be passed as an argument to various orchard functions.

**Comment by bbatsov** [comment]
> An alternative would be to make modifications to the classpath within the session. Would this better reflect what a session is designed to do? The tradeoff is that this would create a specific dependency on the session middleware, and the session object would have to be passed as an argument to various orchard functions.

As Orchard should be usable with other REPLs (e.g. a socket REPL) we can't really exponse any session dependencies in it.
Which functions would need the classloader from the session?

> Before making any changes, it probably makes sense to ask again whether this is the best way to address this.

The best approach would be one that keeps this functionality reusable between REPLs. If that's not feasible, I guess we'll have to move this fully to nREPL.

**Comment by jeffvalk** [comment]
That certainly makes sense.

I pushed a change that addresses this in Orchard without any regard to what the underlying REPL does. It verifies the classpath every time the added resources might be referenced. If the context classloader doesn't share a modifiable ancestor with the previously seen classloader(s), the classpath is updated. It may be a bit brute force in approach, but I think that's a required tradeoff for REPL portability. Regardless, it's simple and works.

**Comment by bbatsov** [comment]
The change looks good to me, I was just wondering about 3rd party Java library sources. Do we need to change something for them to work if they are present on the classpath? 

> An alternative would be to make modifications to the classpath within the session. Would this better reflect what a session is designed to do?

Btw, regarding this alternative approach - do we really need the session itself or just it's classloader? I guess it's fine to add explicit/optional classloader params to functions that might benefit from one.

**Comment by jeffvalk** [comment]
> I was just wondering about 3rd party Java library sources. Do we need to change something for them to work if they are present on the classpath?

No, everything else is the same. This commit doesn't affect the static classpath at all, and shouldn't impact any other dynamic classpath modifications (e.g. from other middleware) either.

> regarding this alternative approach - do we really need the session itself or just it's classloader?

We'd only need its classloader.

**Comment by bbatsov** [comment]
I've cut new Orchard and cider-nrepl releases including the fix. It will soon trickle to CIDER's `master`.

**Comment by bpringe** [comment]
Is there a concrete example of something that didn't work before that works now? I'm not sure if I understand fully what this newly allows / fixes. I tried going to definition on `(System/getenv)` before and after the new version and it doesn't work in either case, but maybe this is not related? Apologies if it's a silly question.

**Comment by bbatsov** [comment]
That's exactly the type of problem that this is supposed to fix. Basically before the fix we'd add the JDK sources to the classpath dynamically, but they weren't in the classloader hierarchy of the REPL sessions and this results in the JDK sources not being available when needed. You do have the JDK sources installed, right?

**Comment by bpringe** [comment]
Not sure... how would I do that? I've installed OpenJDK. If I run `java -version`:

```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
```

Does installing the JDK not install the source? If that's the case, then I guess that means there's a little bit of extra work for a dev to get these features? I assume most people would just install the JDK.

**Comment by bbatsov** [comment]
On Linux the sources are a separate package (at least on Debian-like distros), I'm not sure how it is on other OS-es. You should have a file named `sources.zip` somewhere.

**Comment by bbatsov** [comment]
@jeffvalk Btw, how did you test that this change works? I just got to playing with this myself in CIDER and navigation to code and docs is still broken. E.g. this is what I get for `startsWith`:

```
(-->
  id         "62"
  op         "info"
  session    "f27e4d55-15d0-4176-a18f-a855cbfbb207"
  time-stamp "2021-01-25 11:58:23.932800500"
  ns         #("orchard.misc" 0 12 (fontified t help-echo cider--help-echo cider-locals nil cider-block-dynamic-font-lock t face font-lock-type-face))
  sym        ".startsWith"
)
(<--
  id           "62"
  session      "f27e4d55-15d0-4176-a18f-a855cbfbb207"
  time-stamp   "2021-01-25 11:58:23.934852200"
  arglists-str "[this java.lang.String int]
[this java.lang.String]"
  argtypes     ("java.lang.String" "int")
  class        "java.lang.String"
  javadoc      "https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/String.html#startsWith(java.lang.String,int)"
  member       "startsWith"
  modifiers    "#{:public}"
  returns      "boolean"
  status       ("done")
  throws       nil
)
```

**Comment by jeffvalk** [comment]
Prior to e3de281, I'd only tested launching via `lein`. That commit (in response to [this thread][1]), made things work when launching via the `clojure` executable ...but seems to have stopped it working with `lein`. Annoying.

I just pushed 0768f8e that works with both. I tested it launching both with `lein` and `clojure`, under Java 8 and 11. If you could confirm, that would be excellent.

[1]: https://github.com/clojure-emacs/orchard/commit/fd99c15f962b085e3da7c451eedcb31f7a12c4f6#commitcomment-46301894

**Comment by bbatsov** [comment]
I've tested this now with a locally built ochard and cider-nrepl and it still doesn't work for me:

```
(-->
  id         "37"
  op         "info"
  session    "80915010-2ad6-4b12-84a6-9734b76d938b"
  time-stamp "2021-01-26 09:29:13.725534500"
  ns         "user"
  sym        ".toUpperCase"
)
(<--
  id         "37"
  session    "80915010-2ad6-4b12-84a6-9734b76d938b"
  time-stamp "2021-01-26 09:29:13.727737100"
  candidates (dict
               java.lang.Character (dict
                                     arglists-str "[char]
[int]"
                                     argtypes     ("char")
                                     class        "java.lang.Character"
                                     javadoc      "https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/Character.html#toUpperCase(char)"
                                     member       "toUpperCase"
                                     modifiers    "#{:public :static}"
                                     returns      "char"
                                     throws       nil)
               java.lang.String    (dict
                                     arglists-str "[this]
[this java.util.Locale]"
                                     argtypes     nil
                                     class        "java.lang.String"
                                     javadoc      "https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/lang/String.html#toUpperCase()"
                                     member       "toUpperCase"
                                     modifiers    "#{:public}"
                                     returns      "java.lang.String"
                                     throws       nil))
  status     ("done")
)
```

That's with Lein, JDK 14 and the sources installed.

**Comment by jeffvalk** [comment]
I'm not sure why we're seeing different things. 

Here's what I'm doing to test:

1. Patch `~/.m2/repository/cider/cider-nrepl/cider-nrepl-0.25.8.jar` with 0768f8e.
2. Start either `lein` or `clojure` with:
    ```
    # lein
    /usr/bin/lein update-in :dependencies conj \[nrepl/nrepl\ \"0.8.3\"\] -- update-in :plugins conj \[cider/cider-nrepl\ \"0.25.8\"\] -- repl :headless :host localhost

    # clojure
    /usr/bin/clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version "0.8.3"} cider/cider-nrepl {:mvn/version "0.25.8"}}}' -m nrepl.cmdline --middleware '["cider.nrepl/cider-middleware"]'
    ```
3. Connect via `cider-connect`.
4. In the REPL, type `(.endsWith` and then invoke `cider-doc` or `cider-find-var`.

Here's what I get: 

- When starting via `lein`, I get:
    ```
    (-->
      id         "24"
      op         "info"
      session    "6d7e2a6d-010e-45d6-a9ba-467e9e0bb8f2"
      time-stamp "2021-01-26 11:55:55.327210222"
      ns         "user"
      sym        ".endsWith"
    )
    (<--
      id           "24"
      session      "6d7e2a6d-010e-45d6-a9ba-467e9e0bb8f2"
      time-stamp   "2021-01-26 11:55:55.345323969"
      arglists-str "[this suffix]"
      argtypes     ("java.lang.String")
      class        "java.lang.String"
      column       5
      doc          "Tests if this string ends with the specified suffix. @param ..."
      file         "jar:file:/usr/lib/jvm/java-11-openjdk/lib/src.zip!/java.base..."
      javadoc      "https://docs.oracle.com/en/java/javase/11/docs/api/java.base..."
      line         1484
      member       "endsWith"
      modifiers    "#{:public}"
      resource     "java.base/java/lang/String.java"
      returns      "boolean"
      status       ("done")
      throws       nil
      type         "boolean"
    )
    ```

- When starting via `clojure`, I get:
    ```
    (-->
      id         "23"
      op         "info"
      session    "183eaab9-3643-4ea1-864b-84b373e0c0af"
      time-stamp "2021-01-26 11:53:38.792486893"
      ns         "user"
      sym        ".endsWith"
    )
    (<--
      id           "23"
      session      "183eaab9-3643-4ea1-864b-84b373e0c0af"
      time-stamp   "2021-01-26 11:53:38.800443391"
      arglists-str "[this suffix]"
      argtypes     ("java.lang.String")
      class        "java.lang.String"
      column       5
      doc          "Tests if this string ends with the specified suffix. @param ..."
      file         "java.base/java/lang/String.java"
      javadoc      "https://docs.oracle.com/en/java/javase/11/docs/api/java.base..."
      line         1484
      member       "endsWith"
      modifiers    "#{:public}"
      returns      "boolean"
      status       ("done")
      throws       nil
      type         "boolean"
    )
    ```
    
It's interesting that these differ by `:file` and `:resource`, but they both resolve the source file and `cider-doc` and `cider-find-var` work in both cases.

The results above are using JDK 11. I tested with JDK 8 and got similar results.

What are we doing differently?

**Comment by bbatsov** [comment]
I'm on JDK 14, maybe something changed after JDK 11. That would be my best guess. When I have time I can install JDK 11 to check if the patch works for me there.

**Comment by jeffvalk** [comment]
I just installed JDK 15 to test. It works fine for me, both using `lein` and `clojure` (same test method as above).

**Comment by jeffvalk** [comment]
Are you launching with the inline-dep patched in your `cider-nrepl-*.jar`?

**Comment by bbatsov** [comment]
Yeah. I did a `lein install` for the updated orchard and `make install` for the updated `cider-nrepl`, but there's always the chance I messed something up.

**Comment by jeffvalk** [comment]
If you open the `cider-nrepl-*.jar` and look at `/cider/nrepl/inlined_deps/orchard/*/orchard/java/`, do lines 74-76 look like this:

https://github.com/clojure-emacs/orchard/blob/0768f8ed2be1b8d8f9dea185e72bdacc743c3a7c/src/orchard/java/classpath.clj#L74-L76

...with the `set-classpath!` call *inside* the `modifiable-classloader` call?

**Comment by bbatsov** [comment]
Yep, that's what I see there (in the inlined dep). I aslo see the version of orchard looks good in general (0.6.5, the unreleased one).

**Comment by jeffvalk** [comment]
Two thoughts to try to isolate the cause:

1. When you try a source-dependent function (`cider-doc`, `cider-find-var`, etc) on a core Java class and get no source info, run the following at the REPL, and then try the same call again:
    ```clj
    (reset! cider.nrepl.inlined-deps.orchard.v0v6v5.orchard.java/cache {}) ; modify version as needed
    ```
    If the function returns source info after this, it means the classloader context at initialization is the issue.

4. Have you identified a launch method in which this functionality does work correctly for you? (If it doesn't work via `lein`, does it work via the `clojure` executable, or vice versa?) A more specific failure case would give us a better clue.

**Comment by bpringe** [comment]
I don't mean to interrupt this thread, but a Calva user started seeing an error in the repl, I think inconsistently, I think since we've upgraded cider-nrepl some time ago. See here: https://gist.github.com/gmp26/7fccddb014559990e82c27139ba2cbec. Does this look related to this work?

**Comment by jeffvalk** [comment]
> Does this look related to this work?

Yep, it's related. This one was reported [here][1] and fixed in e3de281.

[1]: https://github.com/clojure-emacs/orchard/commit/fd99c15f962b085e3da7c451eedcb31f7a12c4f6#commitcomment-46301894

**Comment by bbatsov** [comment]
@jeffvalk I was super busy for a few days at work, but I'll make sure to take a closer look at this over the weekend.

**Comment by eamonnsullivan** [comment]
I have discovered that I can turn the issue on and off by switching between Java 8 (on) and Java 11 (off) when running CIDER. Please tell me what other pieces of information might help. I'm running Emacs 28.0.50 (native comp) and using straight.el. I don't know too much about the projects involved here (I'm just a user of them), but since I'm using straight.el I have everything checked out of git locally, so I could throw a debug (message...) into any package, for example. 

I'm on Ubuntu 20.04 and I'm switching between adoptopenjdk-8 and adoptopenjdk-11.

**Comment by bbatsov** [comment]
@eamonnsullivan That happens with `cider-nrepl 0.28.8`, right?

**Comment by eamonnsullivan** [comment]
Yes, that's right. Let me get you the other details.

**Comment by jeffvalk** [comment]
@eamonnsullivan Are you getting the `clojure.lang.Var$Unbound cannot be cast to java.lang.ClassLoader` error mentioned above? Or are you just missing source-dependent features (e.g. jumping into JDK class sources)?

**Comment by eamonnsullivan** [comment]
@jeffvalk , I type something like `(def some-new-thing...` and I get a stack dump in the repl like [this](https://gist.github.com/eamonnsullivan/f1f6e9ce90e194d6cb747ffde254f688).

**Comment by jeffvalk** [comment]
@eamonnsullivan You're seeing this only on Java 8, I presume, not Java 11, correct? Do you see this every time you launch CIDER, or only sometimes?

**Comment by eamonnsullivan** [comment]
I am seeing this only in Java 8 and not in Java 11, that is correct. The observation appears to be consistent -- i.e., it happens every time.

**Comment by RickMoynihan** [comment]
I recently mentioned an issue in `#cider` where ciders nrepl middleware was raising a ClassNotFoundException.  @bbatsov suggested I mention it on this issue and that it might be related.

Periodically in cider I see the following stacktraces which look to be related to pretty printing an exception.  I'm currently using JDK8 with the zulu (azul) build of the JDK, as it ships with some additionally tooling that was removed from openjdk.

```
ERROR: Unhandled REPL handler exception processing message {:nrepl.middleware.print/stream? 1, :nrepl.middleware.print/print cider.nrepl.pprint/pprint, :nrepl.middleware.print/quota 1048576, :nrepl.middleware.print/buffer-size 4096, :nrepl.middleware.print/options {:right-margin 70}, :op stacktrace, :session b224040d-8cde-4685-9066-04816ca55993, :id 912}
java.lang.ClassNotFoundException: com.sun.tools.javac.util.List
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at clojure.lang.RT.classForName(RT.java:2211)
    at clojure.lang.RT.classForName(RT.java:2220)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.java.legacy_parser$parse_java.invokeStatic(legacy_parser.clj:88)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.java.legacy_parser$parse_java.invoke(legacy_parser.clj:66)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.java.legacy_parser$source_info.invokeStatic(legacy_parser.clj:274)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.java.legacy_parser$source_info.invoke(legacy_parser.clj:265)
    at clojure.lang.Var.invoke(Var.java:384)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.java$source_info.invokeStatic(java.clj:144)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.java$source_info.invoke(java.clj:139)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.java$class_info_STAR_.invokeStatic(java.clj:223)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.java$class_info_STAR_.invoke(java.clj:214)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.java$class_info.invokeStatic(java.clj:261)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.java$class_info.invoke(java.clj:253)
    at clojure.core$comp$fn__5807.invoke(core.clj:2569)
    at clojure.lang.Iterate.first(Iterate.java:47)
    at clojure.lang.RT.first(RT.java:692)
    at clojure.core$first__5384.invokeStatic(core.clj:55)
    at clojure.core$take_while$fn__5917.invoke(core.clj:2906)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.RT.seq(RT.java:535)
    at clojure.core$seq__5402.invokeStatic(core.clj:137)
    at clojure.core$filter$fn__5893.invoke(core.clj:2809)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:58)
    at clojure.lang.LazySeq.first(LazySeq.java:73)
    at clojure.lang.RT.first(RT.java:692)
    at clojure.core$first__5384.invokeStatic(core.clj:55)
    at clojure.core$first__5384.invoke(core.clj:55)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.java$member_info.invokeStatic(java.clj:306)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.java$member_info.invoke(java.clj:295)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.java$resolve_member$fn__8223.invoke(java.clj:349)
    at clojure.core$map$fn__5866.invoke(core.clj:2755)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.RT.seq(RT.java:535)
    at clojure.core$seq__5402.invokeStatic(core.clj:137)
    at clojure.core$filter$fn__5893.invoke(core.clj:2809)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:58)
    at clojure.lang.RT.seq(RT.java:535)
    at clojure.lang.RT.nthFrom(RT.java:981)
    at clojure.lang.RT.nth(RT.java:940)
    at clojure.core$distinct$step__6413$fn__6414$fn__6416.invoke(core.clj:5048)
    at clojure.core$distinct$step__6413$fn__6414.invoke(core.clj:5048)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.RT.seq(RT.java:535)
    at clojure.core$seq__5402.invokeStatic(core.clj:137)
    at clojure.core$seq__5402.invoke(core.clj:137)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.java$resolve_symbol.invokeStatic(java.clj:374)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.java$resolve_symbol.invoke(java.clj:357)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.info$clj_meta.invokeStatic(info.clj:76)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.info$clj_meta.invoke(info.clj:65)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.info$info_STAR_.invokeStatic(info.clj:147)
    at cider.nrepl.inlined_deps.orchard.v0v6v4.orchard.info$info_STAR_.invoke(info.clj:136)
    at cider.nrepl.middleware.stacktrace$analyze_fn.invokeStatic(stacktrace.clj:78)
    at cider.nrepl.middleware.stacktrace$analyze_fn.invoke(stacktrace.clj:63)
    at clojure.core$comp$fn__5807.invoke(core.clj:2569)
    at clojure.core$comp$fn__5807.invoke(core.clj:2569)
    at clojure.core$comp$fn__5807.invoke(core.clj:2569)
    at cider.nrepl.middleware.stacktrace$analyze_frame.invokeStatic(stacktrace.clj:180)
    at cider.nrepl.middleware.stacktrace$analyze_frame.invoke(stacktrace.clj:177)
    at clojure.core$map$fn__5866.invoke(core.clj:2755)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.LazySeq.first(LazySeq.java:73)
    at clojure.lang.RT.first(RT.java:692)
    at clojure.core$first__5384.invokeStatic(core.clj:55)
    at clojure.core$first__5384.invoke(core.clj:55)
    at cider.nrepl.middleware.stacktrace$flag_duplicates.invokeStatic(stacktrace.clj:168)
    at cider.nrepl.middleware.stacktrace$flag_duplicates.invoke(stacktrace.clj:164)
    at cider.nrepl.middleware.stacktrace$analyze_stacktrace.invokeStatic(stacktrace.clj:186)
    at cider.nrepl.middleware.stacktrace$analyze_stacktrace.invoke(stacktrace.clj:182)
    at cider.nrepl.middleware.stacktrace$analyze_cause.invokeStatic(stacktrace.clj:290)
    at cider.nrepl.middleware.stacktrace$analyze_cause.invoke(stacktrace.clj:281)
    at cider.nrepl.middleware.stacktrace$analyze_causes$fn__8730.invoke(stacktrace.clj:315)
    at clojure.core$map$fn__5862$fn__5863.invoke(core.clj:2742)
    at clojure.core$take_while$fn__5913$fn__5914.invoke(core.clj:2901)
    at clojure.lang.Iterate.reduce(Iterate.java:81)
    at clojure.core$transduce.invokeStatic(core.clj:6883)
    at clojure.core$into.invokeStatic(core.clj:6899)
    at clojure.core$into.invoke(core.clj:6887)
    at cider.nrepl.middleware.stacktrace$analyze_causes.invokeStatic(stacktrace.clj:314)
    at cider.nrepl.middleware.stacktrace$analyze_causes.invoke(stacktrace.clj:306)
    at cider.nrepl.middleware.stacktrace$handle_stacktrace.invokeStatic(stacktrace.clj:323)
    at cider.nrepl.middleware.stacktrace$handle_stacktrace.invoke(stacktrace.clj:320)
    at clojure.lang.Var.invoke(Var.java:388)
    at cider.nrepl$wrap_stacktrace$fn__2092.invoke(nrepl.clj:417)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at cider.nrepl$wrap_trace$fn__2108.invoke(nrepl.clj:449)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at cider.nrepl$wrap_undef$fn__2124.invoke(nrepl.clj:478)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.core$apply.invokeStatic(core.clj:665)
    at clojure.core$apply.invoke(core.clj:660)
    at sc.nrepl.impl$wrap_handle.invokeStatic(impl.clj:73)
    at sc.nrepl.impl$wrap_handle.invoke(impl.clj:69)
    at sc.nrepl.middleware$wrap_letsc$fn__2466.doInvoke(middleware.clj:13)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at cider.nrepl$wrap_format$fn__2010.invoke(nrepl.clj:189)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at nrepl.middleware.completion$wrap_completion$fn__1434.invoke(completion.clj:50)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at cider.nrepl$wrap_apropos$fn__1968.invoke(nrepl.clj:125)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at cider.nrepl$wrap_version$fn__2134.invoke(nrepl.clj:486)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at cider.nrepl$wrap_clojuredocs$fn__2150.invoke(nrepl.clj:511)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at cider.nrepl$wrap_xref$fn__2142.invoke(nrepl.clj:496)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at cider.nrepl$wrap_complete$fn__1984.invoke(nrepl.clj:139)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at cider.nrepl$wrap_debug$fn__1994.invoke(nrepl.clj:159)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at cider.nrepl$wrap_enlighten$fn__2002.invoke(nrepl.clj:185)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at cider.nrepl$wrap_macroexpand$fn__2036.invoke(nrepl.clj:272)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at cider.nrepl$wrap_refresh$fn__2068.invoke(nrepl.clj:365)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at cider.nrepl$wrap_tracker$fn__2116.invoke(nrepl.clj:467)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at cider.nrepl$wrap_inspect$fn__2028.invoke(nrepl.clj:222)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at nrepl.middleware.caught$wrap_caught$fn__937.invoke(caught.clj:97)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at nrepl.middleware.print$wrap_print$fn__904.invoke(print.clj:234)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at cider.nrepl$wrap_profile$fn__2060.invoke(nrepl.clj:328)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at nrepl.middleware.sideloader$wrap_sideloader$fn__1553.invoke(sideloader.clj:104)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at nrepl.middleware.session$session$fn__1102.invoke(session.clj:309)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at refactor_nrepl.middleware$wrap_refactor$fn__6833.invoke(middleware.clj:196)
    at nrepl.middleware$wrap_conj_descriptor$fn__669.invoke(middleware.clj:16)
    at nrepl.server$default_handler$fn__1597.invoke(server.clj:130)
    at nrepl.server$handle_STAR_.invokeStatic(server.clj:22)
    at nrepl.server$handle_STAR_.invoke(server.clj:19)
    at nrepl.server$handle$fn__1568.invoke(server.clj:39)
    at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by enaeher** [comment]
I'm seeing this as well. With the same version of `cider-nrepl` (0.25.9), I had no problems using `lein repl` and `cider-connect`, but I started to get these `java.lang.ClassNotFoundException: com.sun.tools.javac.util.List` errors in the REPL using the Clojure-cli tools.

**Comment by bbatsov** [comment]
@jeffvalk It seems that a lot of people are running into `java.lang.ClassNotFoundException: com.sun.tools.javac.util.List` with the latest solution. Someone every other day someone mentions this on Slack as well.

**Comment by eamonnsullivan** [comment]
I'm surprised to see this is still an issue -- I cannot work in Cider with Java 8, even though that's a perfectly valid deployment platform. Is there anything I can do to help? I have completely changed laptops since first experiencing this, and reinstalled absolutely everything, and I still can only use Cider with Java 11 (Or, I guess I can pin myself to an earlier version.)

**Comment by bbatsov** [comment]
I'm sorry about the problems this update has caused. I was hoping that @jeffvalk would find time for this, but I guess he has been busy. I won't be able to dive into this any time soon, but I can revert the changes if no one has better ideas.

**Comment by vemv** [comment]
I (ref: earlier in this thread) was long thinking about proposing making all the `dynapath`-related features _opt-out_. This way, these features would be still the default targeted experience, but users would have a way to make things more conservative if they prefered so.

Earlier this week I actually tracked down the root cause of https://github.com/clojure-emacs/cider-nrepl/pull/668 to dynapath in orchard. So there are at least two completely different problems caused by this dependency/implementation.

@bbatsov: would you appreciate if I created a proposal / problem exposition in a separate GH issue? I think things are pretty self-evident by now, but I can also do some writeup.

**Comment by bbatsov** [comment]
@vemv yeah, that'd be great. 

I agree it'd be best to remove dynapath from Orchard and potentially move this responsibility to the Orchard clients. For me it makes sense for them to be doing such classpath modifications if necessary.

**Comment by vemv** [comment]
> @vemv yeah, that'd be great.

Done! https://github.com/clojure-emacs/orchard/issues/113

**Comment by bbatsov** [comment]
Useful resource for people who want to learn more about classloaders and Clojure https://lambdaisland.com/blog/2021-08-25-classpath-is-a-lie

**Comment by vemv** [comment]
For people tracking this issue because of errors such as `java.lang.ClassNotFoundException: com.sun.tools.javac.util.List errors`: they should be fixed in CIDER 1.2 (which was released today) / Orchard 0.8.0.

For the underlying problem (`Modifications to classpath by middleware are not visible to user nREPL session`), we are not using mutable classloaders anymore.
